version: "3.3"

services:
  backend-db:
    env_file:
      - "./backend/node/.env"
    build: ./backend/mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./backend/mysql/db:/var/lib/mysql
    networks:
      - backend

  backend-api:
    build: ./backend/node
    restart: always
    working_dir: /usr/src/app
    command: bash -c "yarn run dev"
    volumes:
      - ./backend/node:/usr/src/app
    depends_on:
      - backend-db
    ports:
      - 8000:8000
    networks:
      - backend
      - frontend

  frontend-app:
    tty: true
    build: ./frontend
    restart: always
    working_dir: /usr/src/app
    command: bash -c "yarn start"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend-api
    ports:
      - 3000:3000
    networks:
      - frontend

networks:
  backend:
  frontend: