# Using node version 16
FROM node:16

# Set the working directory within docker image
WORKDIR /usr/src/app

# May need later on
COPY ./execution-tools/wait-for-it.sh /usr/src/app

# expose port 8000
EXPOSE 8000
